### ISSUE TITLE
Streamline Match Result Notification

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#358]
If you aren't subscribed to a team on both alliances, the match results shouldn't show both alliances

**Comment by fangeugene** [comment]
Should it not?

**Comment by phil-lopreiato** [comment]
It should not, since it doesn't matter who they're competing against (for non-finals matches). Showing both alliances when not subscribed is a waste of space

**Comment by nwalters512** [comment]
I actually like seeing how the opposing alliance did. We could make this an
option in settings. I just don't feel comfortable removing something and
not giving people the option to get it back.

**Comment by phil-lopreiato** [comment]
I think putting an option in settings is the best path.

**Comment by IAmAGitNewbie** [comment]
I (and all of the folks that I become the defacto announcer for) want to know how well both alliances did, not that my watched teams alliance scored XX points.  Having all of that data in the notification saves me a lot time not having to load up the match info to get that information.

I would not want just a single teams / alliances score to be the default to report but I can see having a preference to control it.  Since you are only monitoring a team, would the shorter notification only include that team or would it include all of the alliance members too?

**Comment by phil-lopreiato** [comment]
I was thinking of making an option to show just the alliances your subscribed teams are on (so if two subscribed teams play in the same match on opposite alliances, you still get both scores). 

It's a personal preference which way a user prefers (both alliances or just subscribed ones), and that's why I'm going to put it as a setting and keep them both. I've gotten feedback, which I agree with, that having the scores for an alliance you're not subscribed too is extra clutter. 

The real question is which to make the default option...

**Comment by IAmAGitNewbie** [comment]
Generally when introducing a new behavior the answer is to default to the current behavior and make those who want the new behavior take the expicit actions to change it.  That way those who upgrade are not unhappily surprised at what they would perceive as a loss of data.  "I just upgraded and now my notifications only show half of what they did before.  You broke something in the last update!" is not you want to see posted.

**Comment by phil-lopreiato** [comment]
1 - yeah, that's probably what we're going to do
2 - yes, I've heard that the score notifications were too long and contained information that wasn't explicitly requested.

**Comment by IAmAGitNewbie** [comment]
This thread got me thinking about notification use.  It raised a question that will sound like feature creep but it is worth at least asking now if only to lay groundwork for a future update.

Can we make the notification be configurable to a "win/loss" and/or score setting?

That way users can tune the notification to what they really want from it.  I (and those I relay info to) want both scores primarily to tell if the team won or lost and by how much.   I could easily switch to a "Team XXXX won match ## (### to ##)" notification format over the full info notification since we do not really care who the other teams are unless we are watching them too.  Others may just want to see "Team XXXX won match ##" or "Team XXXX scored ### in match ##".

**Comment by phil-lopreiato** [comment]
The main match result notifications this year are actually a special case for this year's game ([here's](https://github.com/the-blue-alliance/the-blue-alliance-android/issues/326) the issue from when we updated it). You can see all the other strings for that notification [here](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/af63d3f555075d17295e695b3447648fb17bfd3f/android/src/main/res/values/strings_notification.xml#L18).

You'll notice that for finals matches this year, you get the regular W/L/T notification string. And after this year, all notifications will go back to that format. 

With that background, how does what you're proposing fit in with the existing options?

**Comment by IAmAGitNewbie** [comment]
Although FIRST does not declare a winner/looser of each match until the Finals this year, teams still score more, the same or less than the other alliance and we (the teams) still use that verbage and TBA still reports their record in the typical W-L-D format on the full team page.  (I like using the scores over a binary win/loss designation for placement but I will still use the typical verbage when I describe a match.)

I was asking to simplify the notification contents in a couple ways:

1: Only display the watched team(s), not the entire alliance
2: Only display the watched team(s) win/loss status when reporting a match (scores optional)

For example, if I only watch team 2403 then shorten:

Arizona East Regional Quals 81: 5539, 1700, and 4496 scored 48 points; 2840, 3019, and 2403 scored 23 points

to any of the 3 following versions:

Arizona East Regional Quals 81: 2403 scored 23 points (loss)

Arizona East Regional Quals 81: 2403 lost with a score of 23-48

Arizona East Regional Quals 81: 2403 lost

Yes, this may increase the number of resourced strings to cover different permutations when multiple watched teams share the same match.  However I do not think there are a lot of changes given you can put teams on the same alliance into the same string (e.g. "Arizona East Regional Quals 81: 2840, and 2403 lost with a score of 23-48").  

In looking at the available strings I see that my #2 above is already in there although I do not recall ever seeing it.  I rechecked my recent notifications and do not see any that came from the notification_score_teams_won string.  Team 1114 won Waterloo but all I got were:

Waterloo Regional: 2056, 1114, and 5719 beat 3683, 5406, and 1334 in Finals 1 Match 1 with a score of 228-126

Waterloo Regional: 2056, 1114, and 5719 beat 3683, 5406, and 1334 in Finals 1 Match 2 with a score of 264-98

There were no:

Waterloo Regional: 1114 won in Finals 1 Match 1 with a score of 228-126

Waterloo Regional: 1114 won in Finals 1 Match 2 with a score of 264-98

which is primarily what I want.

The closer I look at the notification strings the more I think what I was asking for requires no string changes; perhaps just a little filtering of what gets provided as an input to the string.  For instance notification_score_teams_beat_teams can generate both:

Arizona East Regional Quals 81: 1700 scored 48 points; 2840, and 2403 scored 23 points

and:

Arizona East Regional Quals 81: 1700 scored 48 points; 2403 scored 23 points

I will check the other strings and see if all I am asking for is already there in some fashion other than I just described.  If it is all there already I am curious what it will take to see it (e.g. just 1114's win or 2403s loss notification).

**Comment by phil-lopreiato** [comment]
Even though teams still may reference matches *this year* as won/lost, I want to keep TBA things as close to official as we can, to avoid confusion. This year, the site counts all non-finals matches as ties (for overall WLT calculation) and doesn't display record in an event overview (relevant commits: https://github.com/the-blue-alliance/the-blue-alliance/commit/4b5d790dd31a3e71d5047ea8f3d5b05488ee3126 and https://github.com/the-blue-alliance/the-blue-alliance/commit/8e5b1dd00db361ece1b9ed15ea727aca4f2aee5d). So for 2015 notifications, the one option is to display both alliances, or only the ones containing teams you've subscribed too.

I do not like showing *only* the subscribed teams on an alliances - FRC is and always has been an alliance-centric sport, and I feel like not showing the full alliance would wrongly diminish the other members' contributions. So I feel the minimum unit for score reports is an alliance, not a team. I could be alone here, but the idea just doesn't sit right with me

**Comment by IAmAGitNewbie** [comment]
My goal here was not to try and grossly change the flavor of TBA or the app.  I was merely asking about refining the notification content a little since the topic of notification brevity got me thinking about shortening the data presented in the notifications.

When all 6 teams get reported instead of just the watched teams it can take a minute to determine just how well a watched team did.  For instance:

Arizona East Regional Quals 81: 5539, 1700, and 4496 scored 48 points; 2840, 3019, and 2403 scored 23 points

I have to first scan all team numbers to find the watched one, in this case 2403, and then parse out the separate scores (48 & 23) to finally tell it was a "loss".  My intent was merely to speed up this process.  

Using the aliance as the minimum unit would work for me because it cuts the unused data I have to skip in half.  It would be great if the above were shortened using notification_score_teams_lost to:

Arizona East Regional: 2840, 3019, and 2403 lost in Quals 81 with a score of 23-48

Yes this means that the app would be labeling the alliance with fewer points the match looser even if thats not this years verbage but its how most folks read a score of 23 to 48 no matter what the match type.  

FWIW, the site may be win/loss neutral until the finals but the app is not:

![screenshot_07](https://cloud.githubusercontent.com/assets/2994465/6793498/73965b4c-d182-11e4-97e8-b9dbe6b0a1a2.png)

I actually like both the W-L-D tally and the summary that TBA provides:

Team 1577 was Rank 13 with an average qual score of 56.90 and an average playoff score of 74.00 and won the following awards:...

I wish that the info from the team rankings on the Event ("Qual Avg: 56.9, Litter: 49...") would be available on the teams summary or stats tab along with other event info after the fact (like their rank) but thats a totally separate request and _not_ one I am willing to propose mid way thru the season.

**Comment by phil-lopreiato** [comment]
> My goal here was not to try and grossly change the flavor of TBA or the app. I was merely asking about refining the notification content a little since the topic of notification brevity got me thinking about shortening the data presented in the notifications.

I think we're definitely in agreement about what we're looking for - sorry if I was a little terse about the team v. alliance thing, it's a topic we had some debate about internally

> Using the alliance as the minimum unit would work for me because it cuts the unused data I have to skip in half. It would be great if the above were shortened using notification_score_teams_lost to:
>
> Arizona East Regional: 2840, 3019, and 2403 lost in Quals 81 with a score of 23-48

Maybe we can just change 'won'/'lost' to 'outscored their opponents'/'were outscored in' for this year. Still trying to avoid using the terms won/lost.

> FWIW, the site may be win/loss neutral until the finals but the app is not:

Crap. That shouldn't be there. I don't think it'll be too difficult to hide the record (just for 2015) and add in ranking info. The different average scores for qual/playoff matches will be hard to do here (that data isn't exposed in the API), but I can do the same data you see on the Event Ranking screen. 

> Thanks for listening to my idea and not simply discarding it out of hand.

No problem! Thanks for suggesting ideas (it's no fun when all the GitHub comments are just me talking to myself :P)

**Comment by phil-lopreiato** [comment]
Let's wait and see for next year's game and reevaluate notification strings then

**Comment by 1fish2** [comment]
I think the core problem here is that these messages take too much thinking to read, parse, and find the team numbers you're following. I'd change verbiage in:

> Arizona East Regional Quals 81: 5539, 1700, and 4496 scored 48 points; 2840, 3019, and 2403 scored 23 points

into punctuation and list the followed team(s) first:

> Arizona East Regional Q81
> **1700**/5539/4496: 48 points (win)
> 2840/3019/2403: 23 points

If multiple lines and bold text won't work:

> Arizona East Regional Q81: ★1700★/5539/4496: 48 points (win); 2840/3019/2403: 23 points.

It might still be worth eliding the team numbers on one alliance if you aren't following any of them:

> Arizona East Regional Q81: ★1700★/5539/4496: 48 points (win) vs. 23 points.

I'd try hard to fix it with design rather than a preference setting that few people will discover.
