### ISSUE TITLE
Short event names in notifications

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#380]
Although the Event activity shows short event names like "Silicon Valley", "Philomath", "Pacific Northwest", etc, notifications show long names like "Silicon Valley Regional sponsored by Google.org", "PNW District - Philomath Event", and "Pacific Northwest District Championship".

This is not great for the small display area available and it makes for excess text in frequent match_score and upcoming_match notifications.

The server could send the short event names along with the long event names (as it does for alliance_selection notifications) or instead of the long event names. Or the client could query its local DB for the short names. (Would asynchronous queries be a problem for notification handling?)

**Comment by nwalters512** [comment]
I actually looked into this one already. For many of the notifications,
we're just sending over the appropriate model from the server verbatim,
just converting it to JSON. Adding the short name to that would be
difficult, apparently. And I'm the client side, querying potentially
hundreds of event names with no way to batch them would be rather slow and
inefficient. At least, I think it would be. We can test that.

**Comment by 1fish2** [comment]
Workarounds:

* In the server or client, keep a RAM cache `Map<String event_code, String short_event_name>` for this week's events or recently seen events.
* In the server or client, apply case-insensitive string matching heuristics to the long name:  
    `/(.+) sponsored by .*/` --> `$1`  
    `/.* district - (.+) event/` --> `$1`  
This approach has I18N challenges, but the patterns can be localized.

**Comment by phil-lopreiato** [comment]
For background, you can see exactly what the server sends at this page: http://www.thebluealliance.com/apidocs/webhooks

To elaborate a little...

Some of the notifications send a full event model (alliance selection and awards), which does contain the short name field. The others will often just send the event name/key along with a match model.

I don't like keeping all that data cached locally, I'd prefer to take the regex approach ([also what the server does](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/helpers/event_helper.py#L195)) The patterns won't change, because the event names are all directly scrapped from FIRST, so they'll be whatever the official name on the website is.

**Comment by 1fish2** [comment]
Nice pattern matching. The regex approach sounds good.

I wonder why `alliance_selection` is the only notification with a `short_name` (per the webhooks page).

(A cache would only need the current week's short event names.)

Another approach is to ask FIRST to fix this in their 2016 API.

**Comment by phil-lopreiato** [comment]
There aren't any short names in the API actually, the TBA server calculated them all (I think). And the server doesn't even use the API for event detail, because it doesn't have all the data the lasso pages have. 

The alliances endpoint is the only one that sends a full event model (because alliances are a direct property of that model). Sending anywhere else would be redundant. 

That being said, we can also change what server responses are, so we could add them if we want. I do think doing the regex on notification creation client side is the best approach (it avoids sending redundant data down from the server)

**Comment by 1fish2** [comment]
I'm up for implementing the client-side regex.

Is it too late to do this for 2015? Leave it in a branch? Defer it?

**Comment by nwalters512** [comment]
2015 isn't over yet! From what I've seen it'd be pretty quick to implement,
so if you could do it in a small PR, we could get it live pretty fast.

**Comment by 1fish2** [comment]
:-)
It's just a question of how conservative you want to be with code changes coming up to CMP.

**Comment by phil-lopreiato** [comment]
This doesn't look too bad, so if you can get it done by this weekend (when I want to finalize our CMP release), go for it!

**Comment by 1fish2** [comment]
The code should be straightforward.

But how do you run the tests in an Android Studio test runner? I can run the gradle testDebugBlue task and get web page outputs, but that's not integrated.

**Comment by phil-lopreiato** [comment]
You can run `./gradlew test` to run the test suite. This will also automatically be run when you create a pull request (via travis-ci). 

If you want to run them via Android Studio's interface, you can add a new junit run configuration (hit the down arrow next to the current one, `tba-android`, hit 'edit configurations', and add a new JUnit one for all in the `com.thebluealliance.androidclient.test` package).

It seems like gradle's website is having trouble with their SSL certificate (see the [most recent build](https://travis-ci.org/the-blue-alliance/the-blue-alliance-android)), so it might fail. It's also possible that

**Comment by 1fish2** [comment]
Running a JUnit test for package `com.thebluealliance.androidclient` complains:

> No junit.jar in Module 'the-blue-alliance-android' runtime scope

AS doesn't think there is a package `com.thebluealliance.androidclient.test`.

This avenue is useful but I'll go with the working gradle test run for now and start writing the code.

**Comment by phil-lopreiato** [comment]
That's strange. You should also be able to right click on of the single test files and run as JUnit, if you want just a single file to run. 

JUnit is [defined as a test dependency](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/build.gradle#L147), so I'm not quite sure why you're not seeing it in your classpath. Maybe try doing a project clean?
