### ISSUE TITLE
Issue with myTBA Favorite districts

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance-android#524]
Some districts render as only the key name. Others render properly but show 0 events.
Not sure what the cause is.

![2015-12-25 03 01 35](https://cloud.githubusercontent.com/assets/1421884/11999444/9a180292-aa72-11e5-8e97-ee7124b76d0c.png)

**Comment by phil-lopreiato** [comment]
[Here's the relevant rendering code](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/renderers/MyTbaModelRenderer.java#L85). Some render with key because we weren't able to render the richer model somehow (maybe it wasn't found in the db)?

Not sure about the 0 events thing, maybe some query isn't hooked up somewhere

**Comment by phil-lopreiato** [comment]
The key name thing was fixed with https://github.com/the-blue-alliance/the-blue-alliance/issues/1324 (note how the affected district was from 2014).
