### ISSUE TITLE
Team alliance captain glitch

### ISSUE THREAD

**Issue by AlexNPavel** [the-blue-alliance/the-blue-alliance-android#605]
There is a glitch where every team member part of an alliance is marked as captain of the alliance.

**Comment by nwalters512** [comment]
Can you provide more information? Which event are you seeing this for?

**Comment by AlexNPavel** [comment]
Mt. Olive. I was looking at 8th alliance teams and on their team pages they all say "Captain of 8th alliance"

**Comment by nwalters512** [comment]
I couldn't reproduce that bug; the team@event pages for the 8th alliance teams all properly report captain, first pick, and second pick.

**Comment by AlexNPavel** [comment]
Hmm. Mine still says they're all captains... Refreshing doesn't help either. Maybe it's a bug that only happens under certain circumstances.

**Comment by phil-lopreiato** [comment]
I can reproduce the bug on prod. It shows 1279 as a caption, even though they were ranked 25. I'm out at event now, but I'll post a screenshot when I get back

**Comment by nwalters512** [comment]
Oops, I had the blue debug build installed, I was looking at that instead of prod. I can also reproduce on prod.

**Comment by phil-lopreiato** [comment]
@AlexNPavel can you check this again? It should have "magically" fixed itself.

If so, I found the bug. Currently, TBA only scrapes alliance data from FIRST every 30 minutes (there's an umerged pull to make it faster... https://github.com/the-blue-alliance/the-blue-alliance/pull/1239). This means there is an intermediate time when an elim schedule has been posted, but TBA doesn't know about the specific alliance data yet. When that happens, we only attempt to determine the alliance *number* from the match schedule, not the *pick*. You can see that [here](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/subscribers/TeamAtEventSummarySubscriber.java#L93), where `alliancePick` is not updated in the first case. Once TBA imports alliance data, this bug will no longer be in effect.

Two fix possibilities:
 - In this case, assume picks based on a team's driver station position. We need to verify this is consistent from TBA. `teams` in the alliance object comes in an array, so it should preserve order. We can apply this for 2015+ matches.
 - Otherwise, we'll want to denote "pick unknown" in the code and show it appropriately.

**Comment by fangeugene** [comment]
We can just have it say "On the 8th alliance." This will also scale back to years we don't have alliance selection data for.
