### ISSUE TITLE
FAB for team notifications (yellow star)

### ISSUE THREAD

**Issue by SUPERCILEX** [the-blue-alliance/the-blue-alliance-android#681]
On all teams and events when the yellow FAB shows up the star is full. After checking some boxes the FAB temporarily turns green and then goes back to yellow. I think the star in the FAB should be empty when there are no boxes checked and instead of turning green the star in the FAB should be full (and thus show the current icon). I feel like the current design is misleading: it is indicating that items are checked but this is not true.

**Comment by nwalters512** [comment]
The star was never meant to serve as an indicator for whether a particular model was a favorite or had active subscriptions; it was more so because we needed an icon for the FAB. As for changing colors, that's to indicate success. Green universally means success, red means failure (it turns red if saving the model prefs errors out).

That being said, we could look into changing this. I believe the website uses outlined/full stars to indicate if a model is a favorite.

**Comment by fangeugene** [comment]
I think the color behavior should stay as it is. The filled/empty star could use a change, though -- the site does that.

**Comment by SUPERCILEX** [comment]
Awesome! I wasn't specifically complaining about the green animation, I was just trying to say that it shouldn't be the only one to indicate a subscription. I'd love it if you guys had the star be outlined/filled! :)

**Comment by nwalters512** [comment]
Should the star be filled for both favorites and subscriptions, or just favorites? I'm inclined to say the latter; that's how the site behaves, and the star icon would seem to indicate a favorite.

**Comment by SUPERCILEX** [comment]
I agree, I think the app should be universal with the website. Also, as you pointed out, star means favorite.

**Comment by SUPERCILEX** [comment]
Closing old issues.
