### ISSUE TITLE
Some lamp icons are still old

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance-android#806]
Next to profile pic, on initial load

**Comment by phil-lopreiato** [comment]
Ah, shoot. I guess we aren't using the same resources everywhere.

**Comment by phil-lopreiato** [comment]
We'll also need add a larger lamp icon to the logo repo and update the script from 554f0a82537ebf3cebf641cd4cf43739807cb300. The issue here is that we didn't update [ic_tba_lamp.png](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/res/drawable-xxxhdpi/ic_tba_lamp.png)

**Comment by phil-lopreiato** [comment]
Done in 2d2a422
