### ISSUE TITLE
2017 Match Breakdown RP Wrong

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#818]
https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/views/breakdowns/MatchBreakdownView2017.java#L212

![screenshot_20170304-150546](https://cloud.githubusercontent.com/assets/2754863/23581905/3ecade6a-00ec-11e7-919c-7c36356c8c40.png)

I think this is because we don't always get the alliance data from the other endpoint. We should verify that the score numbers from the breakdown object are actually equal before declaring a tie.

**Comment by 1fish2** [comment]
How about having the server include the RPs rather than trying to maintain such logic in clients?

**Comment by phil-lopreiato** [comment]
@fangeugene thoughts? Can we mutate the score breakdowns and just add our own RP field?

**Comment by fangeugene** [comment]
Drop the field completely? It doesn't show #RP on the site.

**Comment by phil-lopreiato** [comment]
No, I like the field, if anything we should add on the web also

**Comment by fangeugene** [comment]
Then I'll add it to the API. How do we deal with it cross years?

On Mar 4, 2017 6:59 PM, "Phil Lopreiato" <notifications@github.com> wrote:

No, I like the field, if anything we should add on the web also

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/the-blue-alliance/the-blue-alliance-android/issues/818#issuecomment-284194168>,
or mute the thread

**Comment by phil-lopreiato** [comment]
Either backfill it or ignore it and let the app do it for years in the past. I don't really care which
