### ISSUE TITLE
Unable to download data

### ISSUE THREAD

**Issue by agasser** [the-blue-alliance/the-blue-alliance-android#954]
After launching the app I received the "What's new" message and a notice that I needed to download new data. After clicking Next, progress appears at the bottom but when it is downloading District data a message appears.
![Screenshot1](https://user-images.githubusercontent.com/1993518/138310005-78b74682-843d-42bc-91a6-5af97bd5b0a5.png)

**Comment by phil-lopreiato** [comment]
This turned out to be an upstream issue with FIRST's API: it was erroneously returning `eventCode` in the `districtCode` field, which led us to think that every event was its own district.

I filed https://usfirst.collab.net/sf/go/artf6011 as an upstream issue, or we may be able to mitigate on the server side

**Comment by phil-lopreiato** [comment]
I think I was able to do some hackery to fix the existing data server-side, although it may break again if the import job gets run and pulls in more bad data
