### ISSUE TITLE
CCWM calculations are flawed

### ISSUE THREAD

**Issue by inkling16** [the-blue-alliance/the-blue-alliance-android#958]
On the STATS tab for Hueneme Port, I see the following: 
![Screenshot_20220307-125904_The Blue Alliance](https://user-images.githubusercontent.com/5760180/157091410-6f54dad1-eb79-492d-aa8f-9aa91ce7c9c0.jpg)

However, I think something is wrong with either the DPR or CCWM calculations (or both) since by definition CCWM = OPR - DPR.

**Comment by bherbst** [comment]
Since this isn't an issue with the Android client code specifically, I'm going to close this out. 

It looks like https://github.com/the-blue-alliance/the-blue-alliance/issues/4414 in the main web/backend TBA repo is pretty similar and likely the same root issue. If not, feel free to file a new issue there as well!
