### ISSUE TITLE
[BUG] Event selection not going to the correct event

### ISSUE THREAD

**Issue by dracco1993** [the-blue-alliance/the-blue-alliance-android#973]
## Expected Behavior
When I click on an event in the teams listing, it goes to the selected event.

## Current Behavior
Sometimes it goes to the correct event, sometimes it goes to the first event in the list.
I can't figure out any particular reason/pattern to it happening, but it is consistently happening to specific events.

## Steps to Reproduce (for bugs)
1. Search for `1741`
2. Swipe to the `Events` tab
3. Click on the second event (Tippecanoe)
4. Be taken to the first event (Princeton)

## Your Environment

* Version used: 7.0.5
* Operating System and version: Android 13.0 on a Pixel 7 Pro

**Comment by INeedCaffeine** [comment]
I was about to report this as well.  I see this on both a Samsung Galaxy S20 and a Samsung Tab A8 tablet.  Both devices are running Android 13.

I did a little testing and the only pattern I found was the problem happens **only** the first time you do the steps described.  After the first time the actions work as expected.

I reproduce the problem with multiple teams going to multiple events in either 2022 or 2023 so it is not unique to this this year.

**Comment by jaredhasenklein** [comment]
I'm having this problem, too, and recorded my screen showing the behavior.

The reproduce:

1.  Search for `1836` or `254`
2. Click on their championship division
3. TBA opens a different event for the team

I didn't learn much that isn't already in this thread, but:

- The team at event pages clearly exist. At the end of the video, you can see me going to `1836 @ Newton Division` via the `Newton` page rather than team page.

- It seems to be totally random which teams and events are impacted. I test about a dozen teams attending champs across divisions and some had the issue while others didn't. Even teams within the same division at champs don't have the same behavior. For example, `33` and `254` are both on `Archimedes` -- `254` has the problem, `33` doesn't. 

- There is significance with the order of operations. I didn't get it on film, but I had a strange experience with `78` where I clicked on their championship division which displayed correctly, then exited and clicked `Week0` which also displayed correctly, and then each subsequent event I clicked on for that team appeared to be `Week0`.

- I had an **incorrect** theory that this had to do with a team's last event (e.g. if Champs isn't the last event listed for a team in the app, perhaps it was less likely to error out). However, I provided this to be incorrect. Both teams `100` and `111` have two regional events, followed by a Championship division. `111` does not have the issue while `100` does.

---

I'd be curious to know if different users have the same team @ event issues with the app. I don't seem to have the same behavior with `1741` as @dracco1993, but that's also an old report, so I don't know if you're still seeing that exact behavior, Jordan.
